

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";


const kufiArabic = Inter({ subsets: ['latin'], weight: ['100','200','300', '500'] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={kufiArabic.className}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
